<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class AgenteResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            /** This platform's own ID for the agent. Use this for `GET /v1/agents/{id}`, `GET /v1/agents/{id}/printers`, and the test-print endpoint. */
            'id' => $this->id,
            /** Unique ID generated by the agent itself at install time -- stable across reconnects/re-registrations, one per physical machine. */
            'installation_id' => $this->instalacion_id,
            /** Human-readable label set from the agent's own window (e.g. "North Branch -- Register 3"). Null if never set -- fall back to `installation_id`. */
            'display_name' => $this->nombre_descriptivo,
            /** `online` if a heartbeat arrived in the last 60s, otherwise `offline`. */
            'status' => $this->estado,
            /** When the agent's last heartbeat was received. Null if it has never sent one since registering. */
            'last_heartbeat_at' => $this->ultimo_heartbeat,
            /** The printer-agent app version reported in its last heartbeat. */
            'agent_version' => $this->version_agente,
            'created_at' => $this->creado_en,
            /** This agent's configured printers -- only included when explicitly loaded (`GET /v1/agents/{id}` and `GET /v1/agents/{id}/printers`, not the list endpoint). */
            'printers' => ImpresoraResource::collection($this->whenLoaded('impresoras')),
        ];
    }
}
