<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class EventoResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            /** One of the catalog values from the webhooks section: `job.created`, `job.printing`, `job.printed`, `job.failed`, `agent.online`, `agent.offline`. Same values you subscribe a webhook to. */
            'event_type' => $this->tipo_evento,
            /** Raw event data as reported by the agent (or generated by the platform for agent.online/offline transitions) -- shape varies by `event_type`. */
            'payload' => $this->payload,
            'created_at' => $this->creado_en,
        ];
    }
}
