<?php

namespace App\Http\Resources;

use App\Support\JobStatus;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class TrabajoResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            /** This platform's own ID for the job. Use this (not `external_job_id`) when calling `GET /v1/jobs/{id}`. */
            'id' => $this->id,
            /** The agent that printed (or attempted to print) this job. */
            'agent_id' => $this->agente_id,
            /** That agent's human-readable name (falls back to its installation ID if never named) -- only included when the `agente` relation is loaded (list and detail endpoints both load it). */
            'agent_name' => $this->whenLoaded('agente', fn () => $this->agente->nombre_descriptivo ?: $this->agente->instalacion_id),
            /** The specific printer the job was sent to, if it was resolved. Null if the job failed before a printer could be matched. */
            'printer_id' => $this->impresora_id,
            /** Your own job ID, from your POS/back-office system -- whatever you sent as `external_job_id` in the local agent print API (`ws://localhost:8181/ws` or `POST /print`, see the Printing Examples guide). This is how you correlate a platform job back to your own records; it's not generated by PrintBridge. Test-print jobs (triggered from the dashboard, not your POS) get an auto-generated ID here instead -- see `is_test`. */
            'external_job_id' => $this->job_id_externo,
            /** True if this job was triggered from the dashboard's "Send test print" button rather than a real print from your POS. Test jobs still go through the exact same queue/retry/status flow as a real one. */
            'is_test' => str_starts_with($this->job_id_externo, 'prueba-'),
            /** The printer alias this job was sent to (e.g. `receipt`, `wristband`) -- matches the `target` field of the local print job. */
            'target' => $this->target,
            /** The print format used: `raw`, `escpos`, `tspl`, or `html`. */
            'format' => $this->format,
            /** Where the job is in its lifecycle: `pending`, `queued`, `printing`, `printed`, or `failed`. */
            'status' => JobStatus::toApi($this->estado),
            /** How many times the agent has tried to print this job (it retries automatically up to 5 times before giving up). */
            'attempts' => $this->intentos,
            /** The error from the most recent failed attempt, if any. Null while the job is still pending/printing, or once it succeeds. */
            'error_message' => $this->error_mensaje,
            /** How long the actual print took, in milliseconds, once it succeeded. Null until then. */
            'duration_ms' => $this->duracion_ms,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            /** This job's full event history (created, printing, printed/failed) -- only included on `GET /v1/jobs/{id}`, not in the list endpoint. */
            'events' => EventoResource::collection($this->whenLoaded('eventos')),
        ];
    }
}
